import time
print("                 X   X   XXXX   XXX    XXX    X   X")
time.sleep(.1)
print("                 XX XX   X      X  X   X  X    X X ")
time.sleep(.1)
print("                 X X X   XXX    XXX    XXX      X  ")
time.sleep(.1)
print("                 X   X   X      X X    X X      X  ")
time.sleep(.1)
print("                 X   X   XXXX   X  X   X  X     X  ")
time.sleep(.1)
print()
time.sleep(.1)
print("                                 / \\")
time.sleep(.1)
print("                             ___/   \\___")
time.sleep(.1)
print("                             \         /")
time.sleep(.1)
print("                             /__     __\\")
time.sleep(.1)
print("                                \   /")
time.sleep(.1)
print("                                 \ /")
time.sleep(.1)
print("                                 XXX")
time.sleep(.1)
print("                                XXXXX")
time.sleep(.1)
print("                               XXXXXXX")
time.sleep(.1)
print("                              XXXXXXXXX")
time.sleep(.1)
print("                             XXXXXXXXXXX")
time.sleep(.1)
print("                               XXXXXXX")
time.sleep(.1)
print("                              XXXXXXXXX")
time.sleep(.1)
print("                             XXXXXXXXXXX")
time.sleep(.1)
print("                            XXXXXXXXXXXXX")
time.sleep(.1)
print("                           XXXXXXXXXXXXXXX")
time.sleep(.1)
print("                          XXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                            XXXXXXXXXXXXX")
time.sleep(.1)
print("                           XXXXXXXXXXXXXXX")
time.sleep(.1)
print("                          XXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                         XXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                        XXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                       XXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                      XXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                        XXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                       XXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                      XXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                     XXXXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
time.sleep(.1)
print("                               ||||||")
time.sleep(.1)
print("                               ||||||")
time.sleep(.1)
print("                               ||||||")
print()
time.sleep(.1)
print("    XXX   X   X   XXX    XXXXX    XXX   XXXXX   X   X    XXX     XXX")
time.sleep(.1)
print("   X      X   X   X  X     X     X        X     XX XX   X   X   X   ")
time.sleep(.1)
print("   X      XXXXX   XXX      X      XX      X     X X X   XXXXX    XX ")
time.sleep(.1)
print("   X      X   X   X X      X        X     X     X   X   X   X      X")
time.sleep(.1)
print("    XXX   X   X   X  X   XXXXX   XXX      X     X   X   X   X   XXX ")
